### ISSUE TITLE
Create and test a Python package on multiple Python versions

### ISSUE THREAD

**Issue by onyame** [DLR-SC/prov-db-connector#85]
Setup GitHub action for building Python package.

**Comment by B-Stefan** [comment]
I could look into this if you like?

**Comment by B-Stefan** [comment]
@onyame  I think long term it would be a better solution to use GitHub action but I would close this for now due to inactivity. We have a test matrix for all python 3.x versions already configured via Travis ci see https://github.com/DLR-SC/prov-db-connector/runs/4715741391. Also, an automated deployment on a new tag is working. 

If someone would like to add GitHub actions I'm happy to reopen this issue or create a new one.
